### PR TITLE
Azure DevOps pipeline for building binary wheels

### PR DESCRIPTION
**Pull request by afedynitch**
Hi Hans,

this pull request implements Azure DevOps pipelines to build binary wheels for Python 2.7-3.8, Linux, Mac, Windows in 32 and 64bit flavors. The badge in the README tells you that the builds succeed and all tests pass.

To fix some build errors I switched the submodule for HepMC3 from your fork to the one maintained by CERN. There are still some warnings depending on the compiler, but nothing serious since the tests pass.

We also should discuss how you want to trigger Azure, on master, on PR, or for tags. I didn't set up a release pipeline for PyPi yet, that will take the wheels and push them to PyPi. Let me know how you wanna manage this.

### CODE REVIEW

**Comment by HDembinski** [comment]
Wow, this is awesome, thanks. I will merge this. By the way, I became maintainer of the pyhepmc package on PyPI, hence in one of the next patches I should switch to this package name.

**Comment by HDembinski** [comment]
The binary builds should trigger on changes to the master.

**Comment by HDembinski** [comment]
On second thought, the builds should trigger on PRs to the master and on tags, not on changes to the master.

**Comment by afedynitch** [comment]
Great that you'll take over PyPi maintenance of pyhepmc. This will reduce some confusion. To adjust the build pipeline to the new name, change your project including the setup.py, and then change the project name variable in the azure-pipeline-build.yml.

Ping me when you are ready to update the PyPi packages, I will create a release pipeline to upload the binary wheels to PyPi manually or triggered.

**Pull request merged**
